version: "3.3"

volumes:
    langgraph-data:
        driver: local
services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
    langgraph-api:
        image: "my-image"
        ports:
            - "8123:8000"
        extra_hosts:
          - "host.docker.internal:host-gateway"
        depends_on:
        - langgraph-redis
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            OPENAI_API_KEY: <YOUR-API-KEY-HERE>
            LANGSMITH_API_KEY: <YOUR-API-KEY-HERE>
            POSTGRES_URI: postgres://bposeatsuser:bposeatspassword@host.docker.internal:5432/db?sslmode=disable
