version: "3.3"

volumes:
    langgraph-data:
        driver: local
services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5
    langgraph-api:
        image: "langgraph-image"
        ports:
            - "8123:8000"
        extra_hosts:
          - "$POSTGRES_HOST:host-gateway"
        depends_on:
        - langgraph-redis
        env_file:
            - ".env"
